@IH_LibrarySystem_Api_HostAddress = http://localhost:5192
@bookId = 00000000-0000-0000-0000-000000000000
@memberId = 00000000-0000-0000-0000-000000000000

# @name borrowBook
POST {{IH_LibrarySystem_Api_HostAddress}}/api/loans/checkout
Content-Type: application/json

{
  "bookId": "{{bookId}}",
  "memberId": "{{memberId}}"
}

###
@loanId = {{borrowBook.response.body.id}}

GET {{IH_LibrarySystem_Api_HostAddress}}/api/loans/{{loanId}}

###

# @name returnBook
POST {{IH_LibrarySystem_Api_HostAddress}}/api/loans/return/{{loanId}}
Content-Type: application/json

{
  "LoanId": "{{loanId}}",
  "returnDate": "2026-02-05T11:00:00Z"
}

###

# @name getLoansWithFilter
GET {{IH_LibrarySystem_Api_HostAddress}}/api/loans?memberId={{memberId}}&bookId={{bookId}}&isActive=false&isOverdue=false&pageNumber=1&pageSize=10
